# Generated by Django 5.1.5 on 2025-02-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virtualguideapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='Image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tourist_spot',
            name='Image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
