# Generated by Django 5.1.5 on 2025-02-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virtualguideapp', '0002_restaurants_image_tourist_spot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Touristspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Image', models.FileField(blank=True, upload_to='')),
                ('Address', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Tourist_spot',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='Address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
